using Xunit;

namespace Solution.Tests
{
  /// <summary>
  /// The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
  /// - add your own custom tests
  /// - delete existing tests
  /// - modify test contents or expected output
  ///
  /// The results of tests from this file will always be at the beginning of the report generated by clicking the "Run" button.
  ///
  /// The results of these tests do not affect the final score (unless the project fails to build).
  /// </summary>
  [Collection("SandboxTests")]
  [TestCaseOrderer("Solution.Tests.Orderers.AlphabeticalOrderer", "Solution.Tests")]
  public class SandboxTests
  {

    private IntegerContainerBase _container;

    public SandboxTests()
    {
      _container = new IntegerContainer();
    }

    [Fact(DisplayName = "Test sample")]
    public void TestSample()
    {
      Utility.CheckTimeout(() => {
        Assert.Equal(1, _container.Add(5));
        Assert.Equal(2, _container.Add(10));
        Assert.Equal(3, _container.Add(5));
        Assert.True(_container.Delete(10));
        Assert.False(_container.Delete(1));
        Assert.Equal(3, _container.Add(1));
      }, 200);
    }
  }
}
